#!/usr/bin/env bash
# Auto-generated by make_ssf_final_split.py -- session s1, GPU 0.
# 18 cau hinh (moi cai --itr 3); tai uoc luong ~3.0 h.
# Chia bang LPT theo chi phi uoc luong; do not hand-edit -- sua generator roi chay lai.
set -u
if [ ! -d "./logs/ablation-study-2" ]; then mkdir -p "./logs/ablation-study-2"; fi
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
GPU=0

if [ -s "logs/ablation-study-2/ssffinal_AirQuality_1536_96_beta_gamma_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_AirQuality_1536_96_beta_gamma_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_AirQuality_1536_96_beta_gamma_itr3.log"
else
  echo "[ssf-final] AirQuality seq=1536 pred=96 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "AirQuality" --seq_len 1536 --pred_len 96 --freq h --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssffinal_AirQuality_1536_96_beta_gamma_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_AirQuality_1024_96_beta_gamma_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_AirQuality_1024_96_beta_gamma_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_AirQuality_1024_96_beta_gamma_itr3.log"
else
  echo "[ssf-final] AirQuality seq=1024 pred=96 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "AirQuality" --seq_len 1024 --pred_len 96 --freq h --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssffinal_AirQuality_1024_96_beta_gamma_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_AirQuality_1024_192_beta_gamma_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_AirQuality_1024_192_beta_gamma_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_AirQuality_1024_192_beta_gamma_itr3.log"
else
  echo "[ssf-final] AirQuality seq=1024 pred=192 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "AirQuality" --seq_len 1024 --pred_len 192 --freq h --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssffinal_AirQuality_1024_192_beta_gamma_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_AirQuality_1536_96_canonical_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_AirQuality_1536_96_canonical_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_AirQuality_1536_96_canonical_itr3.log"
else
  echo "[ssf-final] AirQuality seq=1536 pred=96 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "AirQuality" --seq_len 1536 --pred_len 96 --freq h --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssffinal_AirQuality_1536_96_canonical_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_AirQuality_1536_336_canonical_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_AirQuality_1536_336_canonical_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_AirQuality_1536_336_canonical_itr3.log"
else
  echo "[ssf-final] AirQuality seq=1536 pred=336 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "AirQuality" --seq_len 1536 --pred_len 336 --freq h --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssffinal_AirQuality_1536_336_canonical_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_Exchange_1536_192_beta_gamma_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_Exchange_1536_192_beta_gamma_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_Exchange_1536_192_beta_gamma_itr3.log"
else
  echo "[ssf-final] Exchange seq=1536 pred=192 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssffinal_Exchange_1536_192_beta_gamma_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_AirQuality_1024_96_canonical_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_AirQuality_1024_96_canonical_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_AirQuality_1024_96_canonical_itr3.log"
else
  echo "[ssf-final] AirQuality seq=1024 pred=96 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "AirQuality" --seq_len 1024 --pred_len 96 --freq h --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssffinal_AirQuality_1024_96_canonical_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_AirQuality_512_192_beta_gamma_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_AirQuality_512_192_beta_gamma_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_AirQuality_512_192_beta_gamma_itr3.log"
else
  echo "[ssf-final] AirQuality seq=512 pred=192 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "AirQuality" --seq_len 512 --pred_len 192 --freq h --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssffinal_AirQuality_512_192_beta_gamma_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_AirQuality_1024_336_canonical_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_AirQuality_1024_336_canonical_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_AirQuality_1024_336_canonical_itr3.log"
else
  echo "[ssf-final] AirQuality seq=1024 pred=336 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "AirQuality" --seq_len 1024 --pred_len 336 --freq h --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssffinal_AirQuality_1024_336_canonical_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_Exchange_1024_192_beta_gamma_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_Exchange_1024_192_beta_gamma_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_Exchange_1024_192_beta_gamma_itr3.log"
else
  echo "[ssf-final] Exchange seq=1024 pred=192 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssffinal_Exchange_1024_192_beta_gamma_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_Exchange_1024_336_beta_gamma_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_Exchange_1024_336_beta_gamma_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_Exchange_1024_336_beta_gamma_itr3.log"
else
  echo "[ssf-final] Exchange seq=1024 pred=336 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssffinal_Exchange_1024_336_beta_gamma_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_Exchange_1536_192_canonical_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_Exchange_1536_192_canonical_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_Exchange_1536_192_canonical_itr3.log"
else
  echo "[ssf-final] Exchange seq=1536 pred=192 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssffinal_Exchange_1536_192_canonical_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_AirQuality_512_192_canonical_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_AirQuality_512_192_canonical_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_AirQuality_512_192_canonical_itr3.log"
else
  echo "[ssf-final] AirQuality seq=512 pred=192 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "AirQuality" --seq_len 512 --pred_len 192 --freq h --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssffinal_AirQuality_512_192_canonical_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_AirQuality_512_336_canonical_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_AirQuality_512_336_canonical_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_AirQuality_512_336_canonical_itr3.log"
else
  echo "[ssf-final] AirQuality seq=512 pred=336 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "AirQuality" --seq_len 512 --pred_len 336 --freq h --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssffinal_AirQuality_512_336_canonical_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_Exchange_512_192_beta_gamma_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_Exchange_512_192_beta_gamma_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_Exchange_512_192_beta_gamma_itr3.log"
else
  echo "[ssf-final] Exchange seq=512 pred=192 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssffinal_Exchange_512_192_beta_gamma_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_Exchange_1024_336_canonical_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_Exchange_1024_336_canonical_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_Exchange_1024_336_canonical_itr3.log"
else
  echo "[ssf-final] Exchange seq=1024 pred=336 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssffinal_Exchange_1024_336_canonical_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_Exchange_512_96_canonical_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_Exchange_512_96_canonical_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_Exchange_512_96_canonical_itr3.log"
else
  echo "[ssf-final] Exchange seq=512 pred=96 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssffinal_Exchange_512_96_canonical_itr3.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssffinal_Exchange_512_192_canonical_itr3.log" ] && [ "$(grep -c 'mse:' "logs/ablation-study-2/ssffinal_Exchange_512_192_canonical_itr3.log" 2>/dev/null)" -ge 3 ]; then
  echo "SKIP (done) logs/ablation-study-2/ssffinal_Exchange_512_192_canonical_itr3.log"
else
  echo "[ssf-final] Exchange seq=512 pred=192 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 3 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssffinal_Exchange_512_192_canonical_itr3.log" 2>&1
fi
echo "[s1/gpu0] DONE"
