#!/usr/bin/env bash
# Auto-generated by make_capacity_split.py -- GPU 1 half of
# capacity-sensitivity.sh's 108-cell grid (round-robin split, see that
# generator's docstring for why). Do not hand-edit; edit
# make_capacity_split.py and regenerate.
set -u
if [ ! -d "./logs/ablation-study-2" ]; then mkdir -p "./logs/ablation-study-2"; fi
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
GPU=1

if [ -s "logs/ablation-study-2/capacity_Exchange_512_96_cd16_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_96_cd16_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_96_cd16_bn16.log"; else
  echo "[capacity] Exchange seq=512 pred=96 cd=16 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --concept_dim 16 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_512_96_cd16_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_96_cd32_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_96_cd32_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_96_cd32_bn8.log"; else
  echo "[capacity] Exchange seq=512 pred=96 cd=32 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --concept_dim 32 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_512_96_cd32_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_96_cd32_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_96_cd32_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_96_cd32_bn32.log"; else
  echo "[capacity] Exchange seq=512 pred=96 cd=32 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --concept_dim 32 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_512_96_cd32_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_96_cd64_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_96_cd64_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_96_cd64_bn16.log"; else
  echo "[capacity] Exchange seq=512 pred=96 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --concept_dim 64 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_512_96_cd64_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_96_cd128_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_96_cd128_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_96_cd128_bn8.log"; else
  echo "[capacity] Exchange seq=512 pred=96 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --concept_dim 128 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_512_96_cd128_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_96_cd128_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_96_cd128_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_96_cd128_bn32.log"; else
  echo "[capacity] Exchange seq=512 pred=96 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --concept_dim 128 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_512_96_cd128_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_192_cd16_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_192_cd16_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_192_cd16_bn16.log"; else
  echo "[capacity] Exchange seq=512 pred=192 cd=16 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --concept_dim 16 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_512_192_cd16_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_192_cd32_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_192_cd32_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_192_cd32_bn8.log"; else
  echo "[capacity] Exchange seq=512 pred=192 cd=32 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --concept_dim 32 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_512_192_cd32_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_192_cd32_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_192_cd32_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_192_cd32_bn32.log"; else
  echo "[capacity] Exchange seq=512 pred=192 cd=32 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --concept_dim 32 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_512_192_cd32_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_192_cd64_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_192_cd64_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_192_cd64_bn16.log"; else
  echo "[capacity] Exchange seq=512 pred=192 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --concept_dim 64 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_512_192_cd64_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_192_cd128_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_192_cd128_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_192_cd128_bn8.log"; else
  echo "[capacity] Exchange seq=512 pred=192 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --concept_dim 128 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_512_192_cd128_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_192_cd128_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_192_cd128_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_192_cd128_bn32.log"; else
  echo "[capacity] Exchange seq=512 pred=192 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --concept_dim 128 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_512_192_cd128_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_336_cd16_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_336_cd16_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_336_cd16_bn16.log"; else
  echo "[capacity] Exchange seq=512 pred=336 cd=16 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --concept_dim 16 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_512_336_cd16_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_336_cd32_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_336_cd32_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_336_cd32_bn8.log"; else
  echo "[capacity] Exchange seq=512 pred=336 cd=32 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --concept_dim 32 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_512_336_cd32_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_336_cd32_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_336_cd32_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_336_cd32_bn32.log"; else
  echo "[capacity] Exchange seq=512 pred=336 cd=32 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --concept_dim 32 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_512_336_cd32_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_336_cd64_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_336_cd64_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_336_cd64_bn16.log"; else
  echo "[capacity] Exchange seq=512 pred=336 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --concept_dim 64 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_512_336_cd64_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_336_cd128_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_336_cd128_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_336_cd128_bn8.log"; else
  echo "[capacity] Exchange seq=512 pred=336 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --concept_dim 128 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_512_336_cd128_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_512_336_cd128_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_512_336_cd128_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_512_336_cd128_bn32.log"; else
  echo "[capacity] Exchange seq=512 pred=336 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --concept_dim 128 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_512_336_cd128_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_96_cd16_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_96_cd16_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_96_cd16_bn16.log"; else
  echo "[capacity] Exchange seq=1024 pred=96 cd=16 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --concept_dim 16 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1024_96_cd16_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_96_cd32_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_96_cd32_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_96_cd32_bn8.log"; else
  echo "[capacity] Exchange seq=1024 pred=96 cd=32 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --concept_dim 32 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1024_96_cd32_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_96_cd32_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_96_cd32_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_96_cd32_bn32.log"; else
  echo "[capacity] Exchange seq=1024 pred=96 cd=32 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --concept_dim 32 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1024_96_cd32_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_96_cd64_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_96_cd64_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_96_cd64_bn16.log"; else
  echo "[capacity] Exchange seq=1024 pred=96 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --concept_dim 64 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1024_96_cd64_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_96_cd128_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_96_cd128_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_96_cd128_bn8.log"; else
  echo "[capacity] Exchange seq=1024 pred=96 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --concept_dim 128 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1024_96_cd128_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_96_cd128_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_96_cd128_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_96_cd128_bn32.log"; else
  echo "[capacity] Exchange seq=1024 pred=96 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --concept_dim 128 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1024_96_cd128_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_192_cd16_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_192_cd16_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_192_cd16_bn16.log"; else
  echo "[capacity] Exchange seq=1024 pred=192 cd=16 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --concept_dim 16 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1024_192_cd16_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_192_cd32_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_192_cd32_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_192_cd32_bn8.log"; else
  echo "[capacity] Exchange seq=1024 pred=192 cd=32 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --concept_dim 32 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1024_192_cd32_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_192_cd32_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_192_cd32_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_192_cd32_bn32.log"; else
  echo "[capacity] Exchange seq=1024 pred=192 cd=32 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --concept_dim 32 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1024_192_cd32_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_192_cd64_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_192_cd64_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_192_cd64_bn16.log"; else
  echo "[capacity] Exchange seq=1024 pred=192 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --concept_dim 64 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1024_192_cd64_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_192_cd128_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_192_cd128_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_192_cd128_bn8.log"; else
  echo "[capacity] Exchange seq=1024 pred=192 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --concept_dim 128 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1024_192_cd128_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_192_cd128_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_192_cd128_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_192_cd128_bn32.log"; else
  echo "[capacity] Exchange seq=1024 pred=192 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --concept_dim 128 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1024_192_cd128_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_336_cd16_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_336_cd16_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_336_cd16_bn16.log"; else
  echo "[capacity] Exchange seq=1024 pred=336 cd=16 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --concept_dim 16 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1024_336_cd16_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_336_cd32_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_336_cd32_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_336_cd32_bn8.log"; else
  echo "[capacity] Exchange seq=1024 pred=336 cd=32 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --concept_dim 32 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1024_336_cd32_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_336_cd32_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_336_cd32_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_336_cd32_bn32.log"; else
  echo "[capacity] Exchange seq=1024 pred=336 cd=32 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --concept_dim 32 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1024_336_cd32_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_336_cd64_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_336_cd64_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_336_cd64_bn16.log"; else
  echo "[capacity] Exchange seq=1024 pred=336 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --concept_dim 64 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1024_336_cd64_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_336_cd128_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_336_cd128_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_336_cd128_bn8.log"; else
  echo "[capacity] Exchange seq=1024 pred=336 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --concept_dim 128 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1024_336_cd128_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1024_336_cd128_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1024_336_cd128_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1024_336_cd128_bn32.log"; else
  echo "[capacity] Exchange seq=1024 pred=336 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --concept_dim 128 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1024_336_cd128_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_96_cd16_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_96_cd16_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_96_cd16_bn16.log"; else
  echo "[capacity] Exchange seq=1536 pred=96 cd=16 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --concept_dim 16 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1536_96_cd16_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_96_cd32_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_96_cd32_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_96_cd32_bn8.log"; else
  echo "[capacity] Exchange seq=1536 pred=96 cd=32 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --concept_dim 32 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1536_96_cd32_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_96_cd32_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_96_cd32_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_96_cd32_bn32.log"; else
  echo "[capacity] Exchange seq=1536 pred=96 cd=32 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --concept_dim 32 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1536_96_cd32_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_96_cd64_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_96_cd64_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_96_cd64_bn16.log"; else
  echo "[capacity] Exchange seq=1536 pred=96 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --concept_dim 64 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1536_96_cd64_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_96_cd128_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_96_cd128_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_96_cd128_bn8.log"; else
  echo "[capacity] Exchange seq=1536 pred=96 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --concept_dim 128 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1536_96_cd128_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_96_cd128_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_96_cd128_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_96_cd128_bn32.log"; else
  echo "[capacity] Exchange seq=1536 pred=96 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --concept_dim 128 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1536_96_cd128_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_192_cd16_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_192_cd16_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_192_cd16_bn16.log"; else
  echo "[capacity] Exchange seq=1536 pred=192 cd=16 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --concept_dim 16 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1536_192_cd16_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_192_cd32_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_192_cd32_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_192_cd32_bn8.log"; else
  echo "[capacity] Exchange seq=1536 pred=192 cd=32 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --concept_dim 32 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1536_192_cd32_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_192_cd32_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_192_cd32_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_192_cd32_bn32.log"; else
  echo "[capacity] Exchange seq=1536 pred=192 cd=32 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --concept_dim 32 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1536_192_cd32_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_192_cd64_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_192_cd64_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_192_cd64_bn16.log"; else
  echo "[capacity] Exchange seq=1536 pred=192 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --concept_dim 64 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1536_192_cd64_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_192_cd128_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_192_cd128_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_192_cd128_bn8.log"; else
  echo "[capacity] Exchange seq=1536 pred=192 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --concept_dim 128 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1536_192_cd128_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_192_cd128_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_192_cd128_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_192_cd128_bn32.log"; else
  echo "[capacity] Exchange seq=1536 pred=192 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --concept_dim 128 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1536_192_cd128_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_336_cd16_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_336_cd16_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_336_cd16_bn16.log"; else
  echo "[capacity] Exchange seq=1536 pred=336 cd=16 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --concept_dim 16 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1536_336_cd16_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_336_cd32_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_336_cd32_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_336_cd32_bn8.log"; else
  echo "[capacity] Exchange seq=1536 pred=336 cd=32 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --concept_dim 32 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1536_336_cd32_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_336_cd32_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_336_cd32_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_336_cd32_bn32.log"; else
  echo "[capacity] Exchange seq=1536 pred=336 cd=32 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --concept_dim 32 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1536_336_cd32_bn32.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_336_cd64_bn16.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_336_cd64_bn16.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_336_cd64_bn16.log"; else
  echo "[capacity] Exchange seq=1536 pred=336 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --concept_dim 64 --bottleneck_dim 16 >> "logs/ablation-study-2/capacity_Exchange_1536_336_cd64_bn16.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_336_cd128_bn8.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_336_cd128_bn8.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_336_cd128_bn8.log"; else
  echo "[capacity] Exchange seq=1536 pred=336 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --concept_dim 128 --bottleneck_dim 8 >> "logs/ablation-study-2/capacity_Exchange_1536_336_cd128_bn8.log" 2>&1
fi
if [ -s "logs/ablation-study-2/capacity_Exchange_1536_336_cd128_bn32.log" ] && grep -q 'mse:' "logs/ablation-study-2/capacity_Exchange_1536_336_cd128_bn32.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/capacity_Exchange_1536_336_cd128_bn32.log"; else
  echo "[capacity] Exchange seq=1536 pred=336 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --concept_dim 128 --bottleneck_dim 32 >> "logs/ablation-study-2/capacity_Exchange_1536_336_cd128_bn32.log" 2>&1
fi
echo "[gpu1] DONE"
