#!/usr/bin/env bash
# Auto-generated by make_kaggle_split.py -- GPU 0 half of the pooled
# ssf-version.sh + encoders.sh job list (round-robin split, see that file's
# docstring for why). Do not hand-edit; edit make_kaggle_split.py and regenerate.
set -u
if [ ! -d "./logs/ablation-study-2" ]; then mkdir -p "./logs/ablation-study-2"; fi
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
GPU=0

if [ -s "logs/ablation-study-2/ssfversion_Exchange_512_96_beta_gamma.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_512_96_beta_gamma.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_512_96_beta_gamma.log"; else
  echo "[ssf-version] Exchange seq=512 pred=96 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssfversion_Exchange_512_96_beta_gamma.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_512_336_beta_gamma.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_512_336_beta_gamma.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_512_336_beta_gamma.log"; else
  echo "[ssf-version] Exchange seq=512 pred=336 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssfversion_Exchange_512_336_beta_gamma.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_1024_192_beta_gamma.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_1024_192_beta_gamma.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_1024_192_beta_gamma.log"; else
  echo "[ssf-version] Exchange seq=1024 pred=192 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssfversion_Exchange_1024_192_beta_gamma.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_1536_96_beta_gamma.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_1536_96_beta_gamma.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_1536_96_beta_gamma.log"; else
  echo "[ssf-version] Exchange seq=1536 pred=96 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssfversion_Exchange_1536_96_beta_gamma.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_1536_336_beta_gamma.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_1536_336_beta_gamma.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_1536_336_beta_gamma.log"; else
  echo "[ssf-version] Exchange seq=1536 pred=336 variant=beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 --ssf_no_input_scale >> "logs/ablation-study-2/ssfversion_Exchange_1536_336_beta_gamma.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_512_192_alpha_beta_gamma.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_512_192_alpha_beta_gamma.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_512_192_alpha_beta_gamma.log"; else
  echo "[ssf-version] Exchange seq=512 pred=192 variant=alpha_beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/ssfversion_Exchange_512_192_alpha_beta_gamma.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_1024_96_alpha_beta_gamma.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_1024_96_alpha_beta_gamma.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_1024_96_alpha_beta_gamma.log"; else
  echo "[ssf-version] Exchange seq=1024 pred=96 variant=alpha_beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/ssfversion_Exchange_1024_96_alpha_beta_gamma.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_1024_336_alpha_beta_gamma.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_1024_336_alpha_beta_gamma.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_1024_336_alpha_beta_gamma.log"; else
  echo "[ssf-version] Exchange seq=1024 pred=336 variant=alpha_beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/ssfversion_Exchange_1024_336_alpha_beta_gamma.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_1536_192_alpha_beta_gamma.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_1536_192_alpha_beta_gamma.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_1536_192_alpha_beta_gamma.log"; else
  echo "[ssf-version] Exchange seq=1536 pred=192 variant=alpha_beta_gamma (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --online_method Proceed --concept_mode dual --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/ssfversion_Exchange_1536_192_alpha_beta_gamma.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_512_96_canonical.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_512_96_canonical.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_512_96_canonical.log"; else
  echo "[ssf-version] Exchange seq=512 pred=96 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssfversion_Exchange_512_96_canonical.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_512_336_canonical.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_512_336_canonical.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_512_336_canonical.log"; else
  echo "[ssf-version] Exchange seq=512 pred=336 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssfversion_Exchange_512_336_canonical.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_1024_192_canonical.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_1024_192_canonical.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_1024_192_canonical.log"; else
  echo "[ssf-version] Exchange seq=1024 pred=192 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssfversion_Exchange_1024_192_canonical.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_1536_96_canonical.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_1536_96_canonical.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_1536_96_canonical.log"; else
  echo "[ssf-version] Exchange seq=1536 pred=96 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssfversion_Exchange_1536_96_canonical.log" 2>&1
fi
if [ -s "logs/ablation-study-2/ssfversion_Exchange_1536_336_canonical.log" ] && grep -q 'mse:' "logs/ablation-study-2/ssfversion_Exchange_1536_336_canonical.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/ssfversion_Exchange_1536_336_canonical.log"; else
  echo "[ssf-version] Exchange seq=1536 pred=336 variant=canonical (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --online_method CanonicalSSF --tune_mode down_up >> "logs/ablation-study-2/ssfversion_Exchange_1536_336_canonical.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_512_192_dual.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_512_192_dual.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_512_192_dual.log"; else
  echo "[encoders] Exchange seq=512 pred=192 mode=dual (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --online_method Proceed --concept_mode dual --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_512_192_dual.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1024_96_dual.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1024_96_dual.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1024_96_dual.log"; else
  echo "[encoders] Exchange seq=1024 pred=96 mode=dual (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --online_method Proceed --concept_mode dual --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1024_96_dual.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1024_336_dual.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1024_336_dual.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1024_336_dual.log"; else
  echo "[encoders] Exchange seq=1024 pred=336 mode=dual (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --online_method Proceed --concept_mode dual --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1024_336_dual.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1536_192_dual.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1536_192_dual.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1536_192_dual.log"; else
  echo "[encoders] Exchange seq=1536 pred=192 mode=dual (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --online_method Proceed --concept_mode dual --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1536_192_dual.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_512_96_shared.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_512_96_shared.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_512_96_shared.log"; else
  echo "[encoders] Exchange seq=512 pred=96 mode=shared (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --online_method Proceed --concept_mode shared --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_512_96_shared.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_512_336_shared.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_512_336_shared.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_512_336_shared.log"; else
  echo "[encoders] Exchange seq=512 pred=336 mode=shared (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --online_method Proceed --concept_mode shared --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_512_336_shared.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1024_192_shared.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1024_192_shared.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1024_192_shared.log"; else
  echo "[encoders] Exchange seq=1024 pred=192 mode=shared (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --online_method Proceed --concept_mode shared --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1024_192_shared.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1536_96_shared.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1536_96_shared.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1536_96_shared.log"; else
  echo "[encoders] Exchange seq=1536 pred=96 mode=shared (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --online_method Proceed --concept_mode shared --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1536_96_shared.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1536_336_shared.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1536_336_shared.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1536_336_shared.log"; else
  echo "[encoders] Exchange seq=1536 pred=336 mode=shared (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --online_method Proceed --concept_mode shared --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1536_336_shared.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_512_192_current.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_512_192_current.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_512_192_current.log"; else
  echo "[encoders] Exchange seq=512 pred=192 mode=current (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --online_method Proceed --concept_mode current --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_512_192_current.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1024_96_current.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1024_96_current.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1024_96_current.log"; else
  echo "[encoders] Exchange seq=1024 pred=96 mode=current (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --online_method Proceed --concept_mode current --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1024_96_current.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1024_336_current.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1024_336_current.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1024_336_current.log"; else
  echo "[encoders] Exchange seq=1024 pred=336 mode=current (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --online_method Proceed --concept_mode current --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1024_336_current.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1536_192_current.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1536_192_current.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1536_192_current.log"; else
  echo "[encoders] Exchange seq=1536 pred=192 mode=current (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --online_method Proceed --concept_mode current --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1536_192_current.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_512_96_strip_y.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_512_96_strip_y.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_512_96_strip_y.log"; else
  echo "[encoders] Exchange seq=512 pred=96 mode=strip_y (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --online_method Proceed --concept_mode strip_y --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_512_96_strip_y.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_512_336_strip_y.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_512_336_strip_y.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_512_336_strip_y.log"; else
  echo "[encoders] Exchange seq=512 pred=336 mode=strip_y (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --online_method Proceed --concept_mode strip_y --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_512_336_strip_y.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1024_192_strip_y.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1024_192_strip_y.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1024_192_strip_y.log"; else
  echo "[encoders] Exchange seq=1024 pred=192 mode=strip_y (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --online_method Proceed --concept_mode strip_y --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1024_192_strip_y.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1536_96_strip_y.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1536_96_strip_y.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1536_96_strip_y.log"; else
  echo "[encoders] Exchange seq=1536 pred=96 mode=strip_y (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --online_method Proceed --concept_mode strip_y --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1536_96_strip_y.log" 2>&1
fi
if [ -s "logs/ablation-study-2/encoders_Exchange_1536_336_strip_y.log" ] && grep -q 'mse:' "logs/ablation-study-2/encoders_Exchange_1536_336_strip_y.log" 2>/dev/null; then echo "SKIP logs/ablation-study-2/encoders_Exchange_1536_336_strip_y.log"; else
  echo "[encoders] Exchange seq=1536 pred=336 mode=strip_y (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --online_method Proceed --concept_mode strip_y --ssf_no_input_scale --concept_dim 32 --bottleneck_dim 32 --ema 0 >> "logs/ablation-study-2/encoders_Exchange_1536_336_strip_y.log" 2>&1
fi
echo "[gpu0] DONE"
