"""
Generates two ready-to-run driver scripts that split capacity-sensitivity.sh's
108-cell grid (cdim x bneck x seq_len x pred_len, Exchange) evenly across 2 GPUs:
capacity_gpu0.sh / capacity_gpu1.sh.

Unlike ssf-version.sh + encoders.sh (which needed pooling because they're two
DIFFERENT-sized scripts), capacity-sensitivity.sh is a single homogeneous grid:
every cell uses the same online_method (Proceed, dual, ssf_no_input_scale) --
no CanonicalSSF-vs-Proceed cost asymmetry to worry about, and the smoke test
already showed per-cell wall time is fairly uniform at a given seq_len anyway.
So a plain round-robin over the grid's own natural iteration order (dataset >
seq_len > pred_len > cdim > bneck) gives a clean 54/54 split, no weighting
needed.

Each emitted job uses the EXACT same flags and log-file naming as
capacity-sensitivity.sh, so results land in the same logs/ablation-study-2/
directory and are recognized by that script's own skip-if-already-run logic
if you later re-run it standalone (e.g. to fill in any cells that failed).

IMPORTANT: if you edit the grid (SEQ_LENS/CDIMS/BNECKS/DATASETS) in
capacity-sensitivity.sh, update the mirrored specs below and re-run this
generator -- it does not read the .sh file, it duplicates its specs.

Usage:
    python3 ttm-scripts/ablation-study-2/make_capacity_split.py
Then, in a Kaggle "GPU T4 x2" session:
    bash ttm-scripts/ablation-study-2/capacity_gpu0.sh &
    bash ttm-scripts/ablation-study-2/capacity_gpu1.sh &
    wait
"""
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_DIR = "logs/ablation-study-2"

SEQ_LENS = [512, 1024, 1536]
CDIMS = [16, 32, 64, 128]
BNECKS = [8, 16, 32]

# dataset spec: name, freq, pred_lens -- mirror capacity-sensitivity.sh exactly
DATASETS = [
    ("Exchange", "d", [96, 192, 336]),
    # ("Jiaolong_DSMS", "s", [96, 192, 336, 720]),  # uncomment to match the .sh file
]

LR = "0.000003"
ITR = "1"
COMMON = ("--model TinyTimeMixer --freeze_online --decoder_mode common_channel "
          "--train_ratio 0.5 --test_ratio 0.45 --batch_size 64 "
          f"--online_learning_rate {LR} --itr {ITR} "
          "--online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0")


def build_jobs():
    jobs = []
    # same loop order as capacity-sensitivity.sh: dataset > seq_len > pred_len > cdim > bneck
    for data, freq, preds in DATASETS:
        for seq_len in SEQ_LENS:
            for pred_len in preds:
                for cdim in CDIMS:
                    for bneck in BNECKS:
                        log = f"{LOG_DIR}/capacity_{data}_{seq_len}_{pred_len}_cd{cdim}_bn{bneck}.log"
                        tag = f"[capacity] {data} seq={seq_len} pred={pred_len} cd={cdim} bn={bneck}"
                        flags = (f'--dataset "{data}" --seq_len {seq_len} --pred_len {pred_len} --freq {freq} '
                                  f'--concept_dim {cdim} --bottleneck_dim {bneck}')
                        jobs.append((log, tag, flags))
    return jobs


def emit(gpu_id, jobs):
    path = os.path.join(OUT_DIR, f"capacity_gpu{gpu_id}.sh")
    lines = [
        "#!/usr/bin/env bash",
        f"# Auto-generated by make_capacity_split.py -- GPU {gpu_id} half of",
        "# capacity-sensitivity.sh's 108-cell grid (round-robin split, see that",
        "# generator's docstring for why). Do not hand-edit; edit",
        "# make_capacity_split.py and regenerate.",
        "set -u",
        f'if [ ! -d "./{LOG_DIR}" ]; then mkdir -p "./{LOG_DIR}"; fi',
        "export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True",
        f"GPU={gpu_id}",
        "",
    ]
    for log, tag, flags in jobs:
        lines += [
            f'if [ -s "{log}" ] && grep -q \'mse:\' "{log}" 2>/dev/null; then echo "SKIP {log}"; else',
            f'  echo "{tag} (gpu=$GPU)"',
            f'  python run.py {COMMON} --gpu $GPU {flags} >> "{log}" 2>&1',
            "fi",
        ]
    lines.append(f'echo "[gpu{gpu_id}] DONE"')
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(path, 0o755)
    return path, len(jobs)


def main():
    jobs = build_jobs()
    gpu0 = jobs[0::2]
    gpu1 = jobs[1::2]
    p0, n0 = emit(0, gpu0)
    p1, n1 = emit(1, gpu1)
    print(f"{len(jobs)} total jobs -> {p0} ({n0} jobs), {p1} ({n1} jobs)")


if __name__ == "__main__":
    main()
