"""
Generates two ready-to-run driver scripts for a Kaggle "GPU T4 x2" session:
kaggle_t4_gpu0.sh / kaggle_t4_gpu1.sh.

Why not just run ssf-version.sh on GPU0 and encoders.sh on GPU1 (one whole
script per GPU)? Because they aren't the same size: ssf-version.sh has 27
cells, encoders.sh has 36 (currently, Exchange-only -- 3 variants/4 modes x 3
seq_lens x 3 preds). Running them as two separate whole-script jobs leaves
GPU0 idle for the last ~1/3 of the run once ssf-version.sh finishes.

Empirically (smoke test, seq_len=512/pred=96, see conversation), per-cell
wall time is fairly UNIFORM across SSF variant / capacity / encoder mode
(231-284s) -- the fixed 3319-step online-test phase dominates, not the
adapter's own compute. Since ssf-version.sh and encoders.sh sweep the exact
same seq_len/pred_len grid, that also means seq_len-driven cost doesn't bias
a split BETWEEN the two scripts. So: pool all 63 jobs from both scripts (in
their original iteration order) into one flat list and alternate GPU0/GPU1
by index -- a plain round-robin, no weighting needed.

Each emitted job uses the EXACT same flags and log-file naming as the
original ssf-version.sh / encoders.sh, so results land in the same
logs/ablation-study-2/ directory and are recognized by those scripts'
own skip-if-already-run logic if you later re-run them standalone.

IMPORTANT: if you edit the grids (SEQ_LENS/DATASETS/VARIANTS/MODES) in
ssf-version.sh or encoders.sh, update the mirrored specs below and re-run
this generator -- it does not read the .sh files, it duplicates their specs.

Usage:
    python3 ttm-scripts/ablation-study-2/make_kaggle_split.py
Then, in a Kaggle "GPU T4 x2" session:
    bash ttm-scripts/ablation-study-2/kaggle_t4_gpu0.sh &
    bash ttm-scripts/ablation-study-2/kaggle_t4_gpu1.sh &
    wait
"""
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_DIR = "logs/ablation-study-2"

SEQ_LENS = [512, 1024, 1536]

# dataset spec: name, freq, pred_lens -- mirror ssf-version.sh / encoders.sh exactly
DATASETS = [
    ("Exchange", "d", [96, 192, 336]),
    # ("Jiaolong_DSMS", "s", [96, 192, 336, 720]),  # uncomment to match the .sh files
]

# ssf-version.sh variants: name, flags
SSF_VARIANTS = [
    ("beta_gamma", "--online_method Proceed --concept_mode dual --concept_dim 32 "
                    "--bottleneck_dim 32 --ema 0 --ssf_no_input_scale"),
    ("alpha_beta_gamma", "--online_method Proceed --concept_mode dual --concept_dim 32 "
                          "--bottleneck_dim 32 --ema 0"),
    ("canonical", "--online_method CanonicalSSF --tune_mode down_up"),
]

# encoders.sh modes
ENCODER_MODES = ["dual", "shared", "current", "strip_y"]

LR = "0.000003"
ITR = "1"
COMMON = ("--model TinyTimeMixer --freeze_online --decoder_mode common_channel "
          "--train_ratio 0.5 --test_ratio 0.45 --batch_size 64 "
          f"--online_learning_rate {LR} --itr {ITR}")


def build_jobs():
    jobs = []
    # ssf-version.sh's 27 jobs, in its original loop order (dataset > variant > seq > pred)
    for data, freq, preds in DATASETS:
        for vname, vflags in SSF_VARIANTS:
            for seq_len in SEQ_LENS:
                for pred_len in preds:
                    log = f"{LOG_DIR}/ssfversion_{data}_{seq_len}_{pred_len}_{vname}.log"
                    tag = f"[ssf-version] {data} seq={seq_len} pred={pred_len} variant={vname}"
                    flags = f'--dataset "{data}" --seq_len {seq_len} --pred_len {pred_len} --freq {freq} {vflags}'
                    jobs.append((log, tag, flags))
    # encoders.sh's 36 jobs, in its original loop order (dataset > mode > seq > pred)
    for data, freq, preds in DATASETS:
        for mode in ENCODER_MODES:
            for seq_len in SEQ_LENS:
                for pred_len in preds:
                    log = f"{LOG_DIR}/encoders_{data}_{seq_len}_{pred_len}_{mode}.log"
                    tag = f"[encoders] {data} seq={seq_len} pred={pred_len} mode={mode}"
                    flags = (f'--dataset "{data}" --seq_len {seq_len} --pred_len {pred_len} --freq {freq} '
                              f'--online_method Proceed --concept_mode {mode} --ssf_no_input_scale '
                              f'--concept_dim 32 --bottleneck_dim 32 --ema 0')
                    jobs.append((log, tag, flags))
    return jobs


def emit(gpu_id, jobs):
    path = os.path.join(OUT_DIR, f"kaggle_t4_gpu{gpu_id}.sh")
    lines = [
        "#!/usr/bin/env bash",
        f"# Auto-generated by make_kaggle_split.py -- GPU {gpu_id} half of the pooled",
        "# ssf-version.sh + encoders.sh job list (round-robin split, see that file's",
        "# docstring for why). Do not hand-edit; edit make_kaggle_split.py and regenerate.",
        "set -u",
        f'if [ ! -d "./{LOG_DIR}" ]; then mkdir -p "./{LOG_DIR}"; fi',
        "export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True",
        f"GPU={gpu_id}",
        "",
    ]
    for log, tag, flags in jobs:
        lines += [
            f'if [ -s "{log}" ] && grep -q \'mse:\' "{log}" 2>/dev/null; then echo "SKIP {log}"; else',
            f'  echo "{tag} (gpu=$GPU)"',
            f'  python run.py {COMMON} --gpu $GPU {flags} >> "{log}" 2>&1',
            "fi",
        ]
    lines.append(f'echo "[gpu{gpu_id}] DONE"')
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(path, 0o755)
    return path, len(jobs)


def main():
    jobs = build_jobs()
    gpu0 = jobs[0::2]
    gpu1 = jobs[1::2]
    p0, n0 = emit(0, gpu0)
    p1, n1 = emit(1, gpu1)
    print(f"{len(jobs)} total jobs -> {p0} ({n0} jobs), {p1} ({n1} jobs)")


if __name__ == "__main__":
    main()
