"""
Sinh 2 driver script chay strip_y encoder ablation tren Exchange (day du 9 cap
seq_len x pred_len, itr=1), cau hinh:
  SSF      : Hypernetwork + affine alpha-beta-gamma (full SSF, KHONG --ssf_no_input_scale)
  Capacity : concept_dim=64, bottleneck_dim=8
  Encoder  : strip_y (co dinh -- day khong phai anchor cua ablation-study-2,
             ma la mot lan chay rieng doi chieu strip_y voi cau hinh cu
             cd64/bn8 + full alpha-beta-gamma tung dung o ttm-scripts/ablation-study/)

9 job (3 seq_len x 3 pred_len), chia deu 2 T4 bang LPT theo cung mo hinh chi
phi da hieu chinh tu smoke test that (xem make_ssf_final_split.py): seq_len
la truc chi phi chinh (1536 ~1.8x so voi 512), pred_len anh huong khong dang
ke o quy mo nay nen chi weight theo seq_len la du.

Log dat ten stripy_cd64bn8_full_Exchange_{seq}_{pred}.log -- KHONG trung voi
encoders_Exchange_*_strip_y.log cua ablation-study-2/encoders.sh (cau hinh
khac: cd32/bn32 + beta_gamma, khong phai cd64/bn8 + full alpha-beta-gamma).

Usage:
    python3 ttm-scripts/ablation-study-2/make_stripy_split.py
Kaggle "GPU T4 x2":
    bash ttm-scripts/ablation-study-2/stripy_gpu0.sh &
    bash ttm-scripts/ablation-study-2/stripy_gpu1.sh &
    wait
"""
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_DIR = "logs/ablation-study-2"
ITR = 1

SEQ_LENS = [512, 1024, 1536]
PRED_LENS = [96, 192, 336]
FREQ = "d"
CDIM, BNECK = 64, 8

FLAGS = (f"--online_method Proceed --concept_mode strip_y "
          f"--concept_dim {CDIM} --bottleneck_dim {BNECK} --ema 0")

COMMON = ("--model TinyTimeMixer --freeze_online --decoder_mode common_channel "
          "--train_ratio 0.5 --test_ratio 0.45 --batch_size 64 "
          f"--online_learning_rate 0.000003 --itr {ITR}")

# he so chi phi tuong doi theo seq_len (xem docstring / make_ssf_final_split.py)
F_SEQ = {512: 1.0, 1024: 1.4, 1536: 1.8}


def build_jobs():
    jobs = []
    for seq_len in SEQ_LENS:
        for pred_len in PRED_LENS:
            log = f"{LOG_DIR}/stripy_cd{CDIM}bn{BNECK}_full_Exchange_{seq_len}_{pred_len}.log"
            tag = f"[strip_y] Exchange seq={seq_len} pred={pred_len}"
            flags = f'--dataset "Exchange" --seq_len {seq_len} --pred_len {pred_len} --freq {FREQ} {FLAGS}'
            jobs.append(dict(log=log, tag=tag, flags=flags, cost=F_SEQ[seq_len]))
    return jobs


def lpt_split(jobs, n_bins=2):
    bins = [[] for _ in range(n_bins)]
    loads = [0.0] * n_bins
    for job in sorted(jobs, key=lambda j: -j["cost"]):
        i = loads.index(min(loads))
        bins[i].append(job)
        loads[i] += job["cost"]
    return bins, loads


def emit(gpu_id, jobs):
    path = os.path.join(OUT_DIR, f"stripy_gpu{gpu_id}.sh")
    lines = [
        "#!/usr/bin/env bash",
        f"# Auto-generated by make_stripy_split.py -- GPU {gpu_id}.",
        f"# strip_y encoder ablation, Exchange, cd={CDIM} bn={BNECK}, full alpha-beta-gamma, itr={ITR}.",
        "# Do not hand-edit -- sua generator roi chay lai.",
        "set -u",
        f'if [ ! -d "./{LOG_DIR}" ]; then mkdir -p "./{LOG_DIR}"; fi',
        "export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True",
        f"GPU={gpu_id}",
        "",
    ]
    for j in jobs:
        log = j["log"]
        lines += [
            f'if [ -s "{log}" ] && grep -q \'mse:\' "{log}" 2>/dev/null; then',
            f'  echo "SKIP (done) {log}"',
            "else",
            f'  echo "{j["tag"]} (gpu=$GPU)"',
            f'  python run.py {COMMON} --gpu $GPU {j["flags"]} >> "{log}" 2>&1',
            "fi",
        ]
    lines.append(f'echo "[gpu{gpu_id}] DONE"')
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(path, 0o755)
    return path


def main():
    jobs = build_jobs()
    bins, loads = lpt_split(jobs)
    print(f"{len(jobs)} cau hinh (Exchange x strip_y x cd{CDIM}/bn{BNECK} x full-SSF, itr={ITR})")
    for gpu_id, (jl, load) in enumerate(zip(bins, loads)):
        p = emit(gpu_id, jl)
        cells = ", ".join(f'{j["tag"].split("seq=")[1]}' for j in jl)
        print(f"  gpu{gpu_id}: {len(jl)} cau hinh (weight {load:.1f}) -> {os.path.basename(p)}  [{cells}]")
    imbalance = (max(loads) - min(loads)) / max(loads) * 100
    print(f"  lech tai giua 2 GPU: {imbalance:.1f}%")


if __name__ == "__main__":
    main()
