#!/usr/bin/env bash
# Auto-generated by make_stripy_split.py -- GPU 0.
# strip_y encoder ablation, Exchange, cd=64 bn=8, full alpha-beta-gamma, itr=1.
# Do not hand-edit -- sua generator roi chay lai.
set -u
if [ ! -d "./logs/ablation-study-2" ]; then mkdir -p "./logs/ablation-study-2"; fi
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
GPU=0

if [ -s "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1536_96.log" ] && grep -q 'mse:' "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1536_96.log" 2>/dev/null; then
  echo "SKIP (done) logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1536_96.log"
else
  echo "[strip_y] Exchange seq=1536 pred=96 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --online_method Proceed --concept_mode strip_y --concept_dim 64 --bottleneck_dim 8 --ema 0 >> "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1536_96.log" 2>&1
fi
if [ -s "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1536_336.log" ] && grep -q 'mse:' "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1536_336.log" 2>/dev/null; then
  echo "SKIP (done) logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1536_336.log"
else
  echo "[strip_y] Exchange seq=1536 pred=336 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --online_method Proceed --concept_mode strip_y --concept_dim 64 --bottleneck_dim 8 --ema 0 >> "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1536_336.log" 2>&1
fi
if [ -s "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1024_336.log" ] && grep -q 'mse:' "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1024_336.log" 2>/dev/null; then
  echo "SKIP (done) logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1024_336.log"
else
  echo "[strip_y] Exchange seq=1024 pred=336 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --online_method Proceed --concept_mode strip_y --concept_dim 64 --bottleneck_dim 8 --ema 0 >> "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_1024_336.log" 2>&1
fi
if [ -s "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_512_192.log" ] && grep -q 'mse:' "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_512_192.log" 2>/dev/null; then
  echo "SKIP (done) logs/ablation-study-2/stripy_cd64bn8_full_Exchange_512_192.log"
else
  echo "[strip_y] Exchange seq=512 pred=192 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --freeze_online --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --online_method Proceed --concept_mode strip_y --concept_dim 64 --bottleneck_dim 8 --ema 0 >> "logs/ablation-study-2/stripy_cd64bn8_full_Exchange_512_192.log" 2>&1
fi
echo "[gpu0] DONE"
