#!/usr/bin/env bash
# Auto-generated by make_capsen_split.py -- GPU 0.
# Capacity sensitivity, Exchange, kich ban 2 (freeze+freeze_online+freeze_bias_after_train),
# dual encoder, beta-gamma SSF (ssf_no_input_scale). Do not hand-edit -- sua generator roi chay lai.
set -u
if [ ! -d "./logs/adapter-only/ablation" ]; then mkdir -p "./logs/adapter-only/ablation"; fi
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
GPU=0

if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd64_bn8.log"
else
  echo "[capsen2] Exchange seq=1536 pred=96 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd64_bn8.log"
else
  echo "[capsen2] Exchange seq=1536 pred=336 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd64_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd64_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd64_bn16.log"
else
  echo "[capsen2] Exchange seq=1536 pred=192 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd64_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd64_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd64_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd64_bn32.log"
else
  echo "[capsen2] Exchange seq=1536 pred=96 cd=64 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd64_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd64_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd64_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd64_bn32.log"
else
  echo "[capsen2] Exchange seq=1536 pred=336 cd=64 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd64_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd128_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd128_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd128_bn8.log"
else
  echo "[capsen2] Exchange seq=1536 pred=192 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd128_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd128_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd128_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd128_bn16.log"
else
  echo "[capsen2] Exchange seq=1536 pred=96 cd=128 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd128_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd128_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd128_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd128_bn16.log"
else
  echo "[capsen2] Exchange seq=1536 pred=336 cd=128 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd128_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd128_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd128_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd128_bn32.log"
else
  echo "[capsen2] Exchange seq=1536 pred=192 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd128_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd256_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd256_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd256_bn8.log"
else
  echo "[capsen2] Exchange seq=1536 pred=96 cd=256 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd256_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd256_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd256_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd256_bn8.log"
else
  echo "[capsen2] Exchange seq=1536 pred=336 cd=256 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd256_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd256_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd256_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd256_bn16.log"
else
  echo "[capsen2] Exchange seq=1536 pred=192 cd=256 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_192_cd256_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd256_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd256_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd256_bn32.log"
else
  echo "[capsen2] Exchange seq=1536 pred=96 cd=256 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_96_cd256_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd256_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd256_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd256_bn32.log"
else
  echo "[capsen2] Exchange seq=1536 pred=336 cd=256 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1536 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_1536_336_cd256_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd64_bn8.log"
else
  echo "[capsen2] Exchange seq=1024 pred=336 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd64_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd64_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd64_bn16.log"
else
  echo "[capsen2] Exchange seq=1024 pred=192 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd64_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd64_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd64_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd64_bn32.log"
else
  echo "[capsen2] Exchange seq=1024 pred=96 cd=64 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd64_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd64_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd64_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd64_bn32.log"
else
  echo "[capsen2] Exchange seq=1024 pred=336 cd=64 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd64_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd128_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd128_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd128_bn8.log"
else
  echo "[capsen2] Exchange seq=1024 pred=192 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd128_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd128_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd128_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd128_bn16.log"
else
  echo "[capsen2] Exchange seq=1024 pred=96 cd=128 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd128_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd128_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd128_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd128_bn16.log"
else
  echo "[capsen2] Exchange seq=1024 pred=336 cd=128 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd128_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd128_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd128_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd128_bn32.log"
else
  echo "[capsen2] Exchange seq=1024 pred=192 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd128_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd256_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd256_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd256_bn8.log"
else
  echo "[capsen2] Exchange seq=1024 pred=96 cd=256 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd256_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd256_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd256_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd256_bn8.log"
else
  echo "[capsen2] Exchange seq=1024 pred=336 cd=256 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd256_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd256_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd256_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd256_bn16.log"
else
  echo "[capsen2] Exchange seq=1024 pred=192 cd=256 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_192_cd256_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd256_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd256_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd256_bn32.log"
else
  echo "[capsen2] Exchange seq=1024 pred=96 cd=256 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_96_cd256_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd256_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd256_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd256_bn32.log"
else
  echo "[capsen2] Exchange seq=1024 pred=336 cd=256 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 1024 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_1024_336_cd256_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_192_cd64_bn8.log"
else
  echo "[capsen2] Exchange seq=512 pred=192 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd64_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd64_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_96_cd64_bn16.log"
else
  echo "[capsen2] Exchange seq=512 pred=96 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd64_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd64_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd64_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_336_cd64_bn16.log"
else
  echo "[capsen2] Exchange seq=512 pred=336 cd=64 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd64_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd64_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd64_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_192_cd64_bn32.log"
else
  echo "[capsen2] Exchange seq=512 pred=192 cd=64 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd64_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd128_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd128_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_96_cd128_bn8.log"
else
  echo "[capsen2] Exchange seq=512 pred=96 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd128_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd128_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd128_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_336_cd128_bn8.log"
else
  echo "[capsen2] Exchange seq=512 pred=336 cd=128 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd128_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd128_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd128_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_192_cd128_bn16.log"
else
  echo "[capsen2] Exchange seq=512 pred=192 cd=128 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd128_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd128_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd128_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_96_cd128_bn32.log"
else
  echo "[capsen2] Exchange seq=512 pred=96 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd128_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd128_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd128_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_336_cd128_bn32.log"
else
  echo "[capsen2] Exchange seq=512 pred=336 cd=128 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 128 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd128_bn32.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd256_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd256_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_192_cd256_bn8.log"
else
  echo "[capsen2] Exchange seq=512 pred=192 cd=256 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd256_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd256_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd256_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_96_cd256_bn16.log"
else
  echo "[capsen2] Exchange seq=512 pred=96 cd=256 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 96 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_512_96_cd256_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd256_bn16.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd256_bn16.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_336_cd256_bn16.log"
else
  echo "[capsen2] Exchange seq=512 pred=336 cd=256 bn=16 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 336 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 16 >> "logs/adapter-only/ablation/capsen2_Exchange_512_336_cd256_bn16.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd256_bn32.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd256_bn32.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Exchange_512_192_cd256_bn32.log"
else
  echo "[capsen2] Exchange seq=512 pred=192 cd=256 bn=32 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Exchange" --seq_len 512 --pred_len 192 --freq d --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 256 --bottleneck_dim 32 >> "logs/adapter-only/ablation/capsen2_Exchange_512_192_cd256_bn32.log" 2>&1
fi
echo "[gpu0] DONE"
