#!/usr/bin/env bash
# Auto-generated by make_jiaolong_split.py -- 1 card (M5000), GPU 0.
# Jiaolong_DSMS, kich ban 2, cd=64/bn=8/dual (guardrail/doi chieu voi capsen Exchange).
# Do not hand-edit -- sua generator roi chay lai.
set -u
if [ ! -d "./logs/adapter-only/ablation" ]; then mkdir -p "./logs/adapter-only/ablation"; fi
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
GPU=${GPU:-0}   # override: GPU=1 bash jiaolong_gpu0.sh

if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_96_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_96_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_96_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=512 pred=96 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 512 --pred_len 96 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_96_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_192_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_192_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_192_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=512 pred=192 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 512 --pred_len 192 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_192_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_336_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_336_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_336_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=512 pred=336 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 512 --pred_len 336 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_336_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_720_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_720_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_720_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=512 pred=720 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 512 --pred_len 720 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_512_720_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_96_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_96_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_96_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=1024 pred=96 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 1024 --pred_len 96 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_96_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_192_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_192_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_192_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=1024 pred=192 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 1024 --pred_len 192 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_192_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_336_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_336_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_336_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=1024 pred=336 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 1024 --pred_len 336 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_336_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_720_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_720_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_720_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=1024 pred=720 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 1024 --pred_len 720 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1024_720_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_96_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_96_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_96_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=1536 pred=96 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 1536 --pred_len 96 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_96_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_192_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_192_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_192_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=1536 pred=192 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 1536 --pred_len 192 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_192_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_336_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_336_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_336_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=1536 pred=336 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 1536 --pred_len 336 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_336_cd64_bn8.log" 2>&1
fi
if [ -s "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_720_cd64_bn8.log" ] && grep -q 'mse:' "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_720_cd64_bn8.log" 2>/dev/null; then
  echo "SKIP (done) logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_720_cd64_bn8.log"
else
  echo "[jiaolong] Jiaolong_DSMS seq=1536 pred=720 cd=64 bn=8 (gpu=$GPU)"
  python run.py --model TinyTimeMixer --decoder_mode common_channel --train_ratio 0.5 --test_ratio 0.45 --batch_size 64 --online_learning_rate 0.000003 --itr 1 --gpu $GPU --dataset "Jiaolong_DSMS" --seq_len 1536 --pred_len 720 --freq s --freeze --freeze_online --freeze_bias_after_train --online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 --concept_dim 64 --bottleneck_dim 8 >> "logs/adapter-only/ablation/capsen2_Jiaolong_DSMS_1536_720_cd64_bn8.log" 2>&1
fi
echo "[gpu0] DONE"
