"""
Sinh 1 driver script chay Jiaolong_DSMS cho kich ban 2 (backbone TTM dong bang
toan bo tu dau den cuoi; bias[-1] hoc trong Phase 1+2, dong bang khi vao Phase 3
-- xem --freeze_bias_after_train), tren 1 card DUY NHAT (M5000 local).

Day la o guardrail/doi chieu voi capsen tren Exchange (xem make_capsen_split.py):
dung dung cd=64/bn=8/dual -- o anchor trong luoi 9 capacity cua capsen. Neu capsen
chot cd64/bn8 (hoac ca luoi phang), ket qua o day duoc GIU LAI lam ket qua Jiaolong
cuoi cung, khong can chay lai. Neu capsen chot mot capacity khac han, script nay
can chay lai voi CDIM/BNECK moi (sua hang so ben duoi, chay lai generator).

Chi 1 GPU -> KHONG can chia tai (LPT); chi liet ke tuan tu ca 12 o.

Log dat ten capsen2_Jiaolong_DSMS_{seq}_{pred}_cd{cd}_bn{bn}.log -- CUNG mot quy
uoc dat ten voi capsen2_Exchange_*.log (make_capsen_split.py), de de doi chieu/
tai su dung neu capacity trung khop.

Usage:
    python3 ttm-scripts/adapter-only/ablation/make_jiaolong_split.py
May M5000 local:
    bash ttm-scripts/adapter-only/ablation/jiaolong_gpu0.sh
"""
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_DIR = "logs/adapter-only/ablation"
ITR = 1

SEQ_LENS = [512, 1024, 1536]
PRED_LENS = [96, 192, 336, 720]
DATA, FREQ = "Jiaolong_DSMS", "s"
CDIM, BNECK = 64, 8

FLAGS = (f"--freeze --freeze_online --freeze_bias_after_train "
          f"--online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0 "
          f"--concept_dim {CDIM} --bottleneck_dim {BNECK}")

COMMON = ("--model TinyTimeMixer --decoder_mode common_channel "
          "--train_ratio 0.5 --test_ratio 0.45 --batch_size 64 "
          f"--online_learning_rate 0.000003 --itr {ITR}")


def build_jobs():
    jobs = []
    for seq_len in SEQ_LENS:
        for pred_len in PRED_LENS:
            log = f"{LOG_DIR}/capsen2_{DATA}_{seq_len}_{pred_len}_cd{CDIM}_bn{BNECK}.log"
            tag = f"[jiaolong] {DATA} seq={seq_len} pred={pred_len} cd={CDIM} bn={BNECK}"
            flags = f'--dataset "{DATA}" --seq_len {seq_len} --pred_len {pred_len} --freq {FREQ} {FLAGS}'
            jobs.append(dict(log=log, tag=tag, flags=flags))
    return jobs


def emit(gpu_id, jobs):
    path = os.path.join(OUT_DIR, f"jiaolong_gpu{gpu_id}.sh")
    lines = [
        "#!/usr/bin/env bash",
        f"# Auto-generated by make_jiaolong_split.py -- 1 card (M5000), GPU {gpu_id}.",
        f"# Jiaolong_DSMS, kich ban 2, cd={CDIM}/bn={BNECK}/dual (guardrail/doi chieu voi capsen Exchange).",
        "# Do not hand-edit -- sua generator roi chay lai.",
        "set -u",
        f'if [ ! -d "./{LOG_DIR}" ]; then mkdir -p "./{LOG_DIR}"; fi',
        "export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True",
        f"GPU=${{GPU:-{gpu_id}}}   # override: GPU=1 bash jiaolong_gpu0.sh",
        "",
    ]
    for j in jobs:
        log = j["log"]
        lines += [
            f'if [ -s "{log}" ] && grep -q \'mse:\' "{log}" 2>/dev/null; then',
            f'  echo "SKIP (done) {log}"',
            "else",
            f'  echo "{j["tag"]} (gpu=$GPU)"',
            f'  python run.py {COMMON} --gpu $GPU {j["flags"]} >> "{log}" 2>&1',
            "fi",
        ]
    lines.append(f'echo "[gpu{gpu_id}] DONE"')
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(path, 0o755)
    return path


def main():
    jobs = build_jobs()
    p = emit(0, jobs)
    print(f"Jiaolong_DSMS: {len(jobs)} cau hinh (cd={CDIM}, bn={BNECK}, dual, itr={ITR}) -> {os.path.basename(p)}")
    print("Chay tuan tu tren 1 card duy nhat -- khong can chia tai.")


if __name__ == "__main__":
    main()
