"""
Sinh 2 driver script chay CONCEPT ENCODER ablation tren Exchange cho kich ban 2
(backbone TTM dong bang toan bo tu dau den cuoi; bias[-1] hoc trong Phase 1+2,
dong bang khi vao Phase 3 -- xem --freeze_bias_after_train), chia deu 2 T4.

*** CDIM/BNECK BEN DUOI LA GIA TRI TAM THOI *** -- se duoc dien lai bang capacity
CHOT tu ket qua capsen (make_capsen_split.py) truoc khi thuc su chay script nay.
Sau khi doi CDIM/BNECK, chay lai generator nay de sinh lai 2 file .sh.

ANCHOR (co dinh trong encoder ablation nay):
  SSF     : Hypernetwork + affine beta-gamma (out-scale + shift, --ssf_no_input_scale)
  Capacity: CDIM/BNECK ben duoi (tam thoi 64/8, cho den khi capsen chot)
  Kich ban: --freeze --freeze_online --freeze_bias_after_train

Chi chay 3 encoder MOI (shared, current, strip_y) -- KHONG chay lai 'dual', vi
capacity CHOT tu capsen chac chan la mot trong 9 o da quet trong capsen2_*.log
(capsen tu no da dung dual lam anchor), nen o dual @ capacity chot da co san
ket qua tu capsen -- xem make_capsen_split.py. Neu sau nay doi y muon co ca 4
encoder trong cung 1 bang, chi can them "dual" vao MODES ben duoi va chay lai.

Log dat ten encoders2_Exchange_{seq}_{pred}_cd{cd}_bn{bn}_{mode}.log -- gan cd/bn
vao ten de biet ro dang chay tren capacity nao (vi gia tri nay se doi khi capsen chot).

Usage:
    python3 ttm-scripts/adapter-only/ablation/make_encoders_split.py
Kaggle "GPU T4 x2":
    bash ttm-scripts/adapter-only/ablation/encoders_gpu0.sh &
    bash ttm-scripts/adapter-only/ablation/encoders_gpu1.sh &
    wait
"""
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_DIR = "logs/adapter-only/ablation"
ITR = 1

SEQ_LENS = [512, 1024, 1536]
PRED_LENS = [96, 192, 336]
FREQ = "d"

# *** TAM THOI -- dien lai bang capacity CHOT tu capsen, roi chay lai generator nay ***
CDIM, BNECK = 64, 8

MODES = ["shared", "current", "strip_y"]   # KHONG co 'dual' -- xem docstring

FLAGS = (f"--freeze --freeze_online --freeze_bias_after_train "
          f"--online_method Proceed --ssf_no_input_scale --ema 0 "
          f"--concept_dim {CDIM} --bottleneck_dim {BNECK}")

COMMON = ("--model TinyTimeMixer --decoder_mode common_channel "
          "--train_ratio 0.5 --test_ratio 0.45 --batch_size 64 "
          f"--online_learning_rate 0.000003 --itr {ITR}")

# he so chi phi tuong doi theo seq_len (xem make_capsen_split.py)
F_SEQ = {512: 1.0, 1024: 1.4, 1536: 1.8}


def build_jobs():
    jobs = []
    for mode in MODES:
        for seq_len in SEQ_LENS:
            for pred_len in PRED_LENS:
                log = f"{LOG_DIR}/encoders2_Exchange_{seq_len}_{pred_len}_cd{CDIM}_bn{BNECK}_{mode}.log"
                tag = f"[encoders2] Exchange seq={seq_len} pred={pred_len} cd={CDIM} bn={BNECK} mode={mode}"
                flags = (f'--dataset "Exchange" --seq_len {seq_len} --pred_len {pred_len} --freq {FREQ} '
                          f'{FLAGS} --concept_mode {mode}')
                jobs.append(dict(log=log, tag=tag, flags=flags, cost=F_SEQ[seq_len]))
    return jobs


def lpt_split(jobs, n_bins=2):
    bins = [[] for _ in range(n_bins)]
    loads = [0.0] * n_bins
    for job in sorted(jobs, key=lambda j: -j["cost"]):
        i = loads.index(min(loads))
        bins[i].append(job)
        loads[i] += job["cost"]
    return bins, loads


def emit(gpu_id, jobs):
    path = os.path.join(OUT_DIR, f"encoders_gpu{gpu_id}.sh")
    lines = [
        "#!/usr/bin/env bash",
        f"# Auto-generated by make_encoders_split.py -- GPU {gpu_id}.",
        f"# Encoder ablation, Exchange, kich ban 2, cd={CDIM}/bn={BNECK} (TAM THOI -- xem docstring generator),",
        "# beta-gamma SSF (ssf_no_input_scale), 3 encoder moi (shared/current/strip_y).",
        "# Do not hand-edit -- sua generator roi chay lai.",
        "set -u",
        f'if [ ! -d "./{LOG_DIR}" ]; then mkdir -p "./{LOG_DIR}"; fi',
        "export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True",
        f"GPU={gpu_id}",
        "",
    ]
    for j in jobs:
        log = j["log"]
        lines += [
            f'if [ -s "{log}" ] && grep -q \'mse:\' "{log}" 2>/dev/null; then',
            f'  echo "SKIP (done) {log}"',
            "else",
            f'  echo "{j["tag"]} (gpu=$GPU)"',
            f'  python run.py {COMMON} --gpu $GPU {j["flags"]} >> "{log}" 2>&1',
            "fi",
        ]
    lines.append(f'echo "[gpu{gpu_id}] DONE"')
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(path, 0o755)
    return path


def main():
    jobs = build_jobs()
    bins, loads = lpt_split(jobs)
    print(f"Capacity dang dung (TAM THOI): cdim={CDIM}, bneck={BNECK}")
    print(f"{len(jobs)} cau hinh (Exchange x {len(MODES)} encoder x 9 o, itr={ITR})")
    for gpu_id, (jl, load) in enumerate(zip(bins, loads)):
        p = emit(gpu_id, jl)
        print(f"  gpu{gpu_id}: {len(jl)} cau hinh (weight {load:.1f}) -> {os.path.basename(p)}")
    imbalance = (max(loads) - min(loads)) / max(loads) * 100
    print(f"  lech tai giua 2 GPU: {imbalance:.1f}%")


if __name__ == "__main__":
    main()
