"""
Sinh 2 driver script chay CAPACITY SENSITIVITY (capsen) tren Exchange cho kich
ban 2 (backbone TTM dong bang toan bo tu dau den cuoi; bias[-1] ton tai, hoc
trong Phase 1+2, dong bang khi vao Phase 3 -- xem --freeze_bias_after_train,
adapter/proceed.py + exp/exp_proceed.py), chia deu 2 T4.

ANCHOR (co dinh trong capsen nay):
  Encoder : dual
  SSF     : Hypernetwork + affine beta-gamma (out-scale + shift, --ssf_no_input_scale)
  Kich ban: --freeze --freeze_online --freeze_bias_after_train

Truc dang quet: concept_dim x bottleneck_dim = {64,128,256} x {8,16,32} = 9 capacity,
tren day du 9 o (seq_len in {512,1024,1536} x pred_len in {96,192,336}) cua Exchange,
itr=1 => 81 lan chay.

Chia LPT theo trong so seq_len (nhu cac generator truoc: 1536 ~1.8x so voi 512;
cdim/bneck khong doi chi phi dang ke o quy mo nay nen khong weight theo truc do).

Log dat ten capsen2_Exchange_{seq}_{pred}_cd{cd}_bn{bn}.log -- them "2" de phan
biet voi cac capacity-sensitivity truoc do (kich ban 1, khong co freeze_bias_after_train).

Usage:
    python3 ttm-scripts/adapter-only/ablation/make_capsen_split.py
Kaggle "GPU T4 x2":
    bash ttm-scripts/adapter-only/ablation/capsen_gpu0.sh &
    bash ttm-scripts/adapter-only/ablation/capsen_gpu1.sh &
    wait
"""
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
LOG_DIR = "logs/adapter-only/ablation"
ITR = 1

SEQ_LENS = [512, 1024, 1536]
PRED_LENS = [96, 192, 336]
FREQ = "d"
CDIMS = [64, 128, 256]
BNECKS = [8, 16, 32]

FLAGS = ("--freeze --freeze_online --freeze_bias_after_train "
          "--online_method Proceed --concept_mode dual --ssf_no_input_scale --ema 0")

COMMON = ("--model TinyTimeMixer --decoder_mode common_channel "
          "--train_ratio 0.5 --test_ratio 0.45 --batch_size 64 "
          f"--online_learning_rate 0.000003 --itr {ITR}")

# he so chi phi tuong doi theo seq_len (xem make_ssf_final_split.py / make_stripy_split.py)
F_SEQ = {512: 1.0, 1024: 1.4, 1536: 1.8}


def build_jobs():
    jobs = []
    for cdim in CDIMS:
        for bneck in BNECKS:
            for seq_len in SEQ_LENS:
                for pred_len in PRED_LENS:
                    log = f"{LOG_DIR}/capsen2_Exchange_{seq_len}_{pred_len}_cd{cdim}_bn{bneck}.log"
                    tag = f"[capsen2] Exchange seq={seq_len} pred={pred_len} cd={cdim} bn={bneck}"
                    flags = (f'--dataset "Exchange" --seq_len {seq_len} --pred_len {pred_len} --freq {FREQ} '
                              f'{FLAGS} --concept_dim {cdim} --bottleneck_dim {bneck}')
                    jobs.append(dict(log=log, tag=tag, flags=flags, cost=F_SEQ[seq_len]))
    return jobs


def lpt_split(jobs, n_bins=2):
    bins = [[] for _ in range(n_bins)]
    loads = [0.0] * n_bins
    for job in sorted(jobs, key=lambda j: -j["cost"]):
        i = loads.index(min(loads))
        bins[i].append(job)
        loads[i] += job["cost"]
    return bins, loads


def emit(gpu_id, jobs):
    path = os.path.join(OUT_DIR, f"capsen_gpu{gpu_id}.sh")
    lines = [
        "#!/usr/bin/env bash",
        f"# Auto-generated by make_capsen_split.py -- GPU {gpu_id}.",
        "# Capacity sensitivity, Exchange, kich ban 2 (freeze+freeze_online+freeze_bias_after_train),",
        "# dual encoder, beta-gamma SSF (ssf_no_input_scale). Do not hand-edit -- sua generator roi chay lai.",
        "set -u",
        f'if [ ! -d "./{LOG_DIR}" ]; then mkdir -p "./{LOG_DIR}"; fi',
        "export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True",
        f"GPU={gpu_id}",
        "",
    ]
    for j in jobs:
        log = j["log"]
        lines += [
            f'if [ -s "{log}" ] && grep -q \'mse:\' "{log}" 2>/dev/null; then',
            f'  echo "SKIP (done) {log}"',
            "else",
            f'  echo "{j["tag"]} (gpu=$GPU)"',
            f'  python run.py {COMMON} --gpu $GPU {j["flags"]} >> "{log}" 2>&1',
            "fi",
        ]
    lines.append(f'echo "[gpu{gpu_id}] DONE"')
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(path, 0o755)
    return path


def main():
    jobs = build_jobs()
    bins, loads = lpt_split(jobs)
    print(f"{len(jobs)} cau hinh (Exchange x capsen 3x3 x full grid 3x3, itr={ITR})")
    for gpu_id, (jl, load) in enumerate(zip(bins, loads)):
        p = emit(gpu_id, jl)
        print(f"  gpu{gpu_id}: {len(jl)} cau hinh (weight {load:.1f}) -> {os.path.basename(p)}")
    imbalance = (max(loads) - min(loads)) / max(loads) * 100
    print(f"  lech tai giua 2 GPU: {imbalance:.1f}%")


if __name__ == "__main__":
    main()
